language: go
go:
- 1.x
before_deploy:
- GOOS=linux GOARCH=amd64 go build -ldflags="-s -w" -o departures
- tar -czf departures_linux_amd64.tar.gz departures README.md LICENSE
- GOOS=linux GOARCH=386 go build -ldflags="-s -w" -o departures
- tar -czf departures_linux_386.tar.gz departures README.md LICENSE
- GOOS=darwin GOARCH=amd64 go build -ldflags="-s -w" -o departures
- tar -czf departures_macos_amd64.tar.gz departures README.md LICENSE
- GOOS=freebsd GOARCH=amd64 go build -ldflags="-s -w" -o departures
- tar -czf departures_freebsd_amd64.tar.gz departures README.md LICENSE
- GOOS=freebsd GOARCH=386 go build -ldflags="-s -w" -o departures
- tar -czf departures_freebsd_386.tar.gz departures README.md LICENSE
- GOOS=linux GOARCH=arm GOARM=5 go build -ldflags="-s -w" -o departures
- tar -czf departures_raspi.tar.gz departures README.md LICENSE
deploy:
  provider: releases
  api_key:
    secure: Hy3XwP21yZ7VaxfzOQuZokpyTkij5vTJRXF6r98bAf0Au2PHcjGywDP/4DZycYw4te/7vUkeCau3T4E3/sbMxqSu8s/sl+uCY9BGRzuBbpO2wn6xzXdMQI+EinWiGqGrSgZE8tvTJkG/1x0jG6A4XibiihB7u0nLP3277+CZ15jc7b0MffAP9le0VubsaTGupiq7v698HAtIkkB6pPiVTKykBLdoGrC/38Hyoxi3KJdq71vrK9j1MDdZ9BdJjNiEp+r4HnKszhauOFbCiQCsA2Ayd7Iz7RmV0rqE7YgwknP8+MaCJeydZQOvce1yV/qsnr1iHJGikicM2UV+9MSztmrIKMvaxZ35Bv4u4vOsg4IFvXLxl82mYzeOEOQ9SqiFTBX7ag8ZZJSJZapNkyEXGyJSnGsBrDRC+HwMHPKwqHy+BXGUiqTcHYSuDxl8OK6mLEOb0MIjbAgSUtQHPTMdHQjFecrEi5hWpounW7rZSNB5e5zDldgS+6NRcFDrfSmA71Nvr4wJzIG/aLQPFlDe3B9gVajHevvzDfo0N/MUh8eTQrcs8l4Kx6/WDdu5s09RlD4HKhiM9Hwr25OCqvjHf8q14JaMexXh7iYywqn+Q6k2M/JW7kNEMtmMbFHRRsnZIey9towOVjsR9WWqYOQyD6wTejyAzhNWTiTMkQHsY3I=
  file:
  - departures_linux_amd64.tar.gz
  - departures_linux_386.tar.gz
  - departures_macos_amd64.tar.gz
  - departures_freebsd_amd64.tar.gz
  - departures_freebsd_386.tar.gz
  - departures_raspi.tar.gz
  skip_cleanup: true
  draft: true
  on:
    repo: noxer/departures
    tags: true
